[general]
version = "1.0"
type = "databricks"
bundle-name = "dev"
productive = false

[databricks]
app-name = "ai-pengui-workflow"
workspace-url = "/Workspace/Users/german.gomez@consultants.lgads.tv/agiv-fast-deployment"
host = "https://dbc-3b4bc42a-bf11.cloud.databricks.com"
pat-secret-name = "deploy-dev-pat"
fontend-app-name = "dev-internal"
platform-backend-app-name = "dev-ai-platform-backend"
iceberg-app-name = "dev-pengui-iceberg"
